/**
 * Authentication & Profile types
 * Source: supabase/migrations/00001_create_profiles.sql
 */

// ============================================================
// profiles
// ============================================================

export type Profile = {
  id: string
  user_id: string
  display_name: string | null
  avatar_url: string | null
  total_xp: number
  current_level: number
  created_at: string
  updated_at: string
}

/** Profile insert — id, timestamps auto-generated by DB */
export type ProfileInsert = Omit<Profile, 'id' | 'created_at' | 'updated_at'>

/**
 * Profile update — explicit null clears the field (DB allows null).
 * FIX (finding #15): Make clear that sending null means "clear this field".
 */
export type ProfileUpdate = {
  display_name?: string | null
  avatar_url?: string | null
}
